events {}

http {

upstream backend_servers {

    server backend1:5000;

    server backend2:5000;

}

server {

    listen 80;

    root /usr/share/nginx/html;

    index login.html;

    # =========================
    # FRONTEND
    # =========================

    location / {

        try_files $uri $uri/ /login.html;

    }

    # =========================
    # BACKEND API
    # =========================

    location /api/ {

        proxy_pass http://backend_servers/;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }

}

}