

events {}

http {

    # =====================================
    # BACKEND LOAD BALANCER
    # =====================================

    upstream backend_servers {

        server backend_api_1:5000;

        server backend_api_2:5000;

    }

    # =====================================
    # SERVER
    # =====================================

    server {

        listen 80;

        root /usr/share/nginx/html;

        index login.html;

        # =====================================
        # FRONTEND
        # =====================================

        location / {

            try_files $uri $uri/ /login.html;

        }

        # =====================================
        # API BACKEND
        # =====================================

        location /api/ {

            proxy_pass http://backend_servers;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

    }

}
